#!/usr/bin/env bash

CFLAGS="${CFLAGS} -g3 -O0 -fno-inline -fno-omit-frame-pointer"
CXXFLAGS="${CXXFLAGS} -g3 -O0 -fno-inline -fno-omit-frame-pointer"
export CFLAGS CXXFLAGS

./build-debug --disable-dynamic-core "${@}"
